
# Ejercicio final: Extraer información de un archivo JSON usando expresiones regulares (regex)


## Objetivo:

El objetivo de este ejercicio es practicar la utilización de expresiones regulares (regex) para extraer información específica de un archivo JSON. El ejercicio se enfocará en la lectura y análisis de un archivo JSON que contiene información sobre clientes.

## Descripción:

### Obtener el archivo JSON:
Lea archivo JSON 'clientes.json' que contiene la información sobre clientes. El archivo debe tener una estructura similar a la siguiente:

In [66]:
{
  "clientes": [
    {
      "nombre": "Juan PÃ©rez",
      "direccion": "Calle Mayor 123",
      "ciudad": "San JosÃ©",
      "telefono": "+506 2222-3333"
    },
    {
      "nombre": "MarÃ­a GÃ³mez",
      "direccion": "Avenida Central 456",
      "ciudad": "Alajuela",
      "telefono": "+506 8888-4444"
    },
    {
      "nombre": "Pedro RamÃ­rez",
      "direccion": "Barrio Escalante 789",
      "ciudad": "Heredia",
      "telefono": "+506 5555-6666"
    },
    {
      "nombre": "Ana Castro",
      "direccion": "Avenida 10 Calle 5",
      "ciudad": "Cartago",
      "telefono": "+506 3333-4444"
    },
    {
      "nombre": "Carlos JimÃ©nez",
      "direccion": "Calle Principal 12",
      "ciudad": "Liberia",
      "telefono": "+506 6666-7777"
    },
    {
      "nombre": "Diana Solano",
      "direccion": "Barrio La UniÃ³n 78",
      "ciudad": "Puntarenas",
      "telefono": "+506 9999-8888"
    }
  ]
}

{'clientes': [{'nombre': 'Juan PÃ©rez',
   'direccion': 'Calle Mayor 123',
   'ciudad': 'San JosÃ©',
   'telefono': '+506 2222-3333'},
  {'nombre': 'MarÃ\xada GÃ³mez',
   'direccion': 'Avenida Central 456',
   'ciudad': 'Alajuela',
   'telefono': '+506 8888-4444'},
  {'nombre': 'Pedro RamÃ\xadrez',
   'direccion': 'Barrio Escalante 789',
   'ciudad': 'Heredia',
   'telefono': '+506 5555-6666'},
  {'nombre': 'Ana Castro',
   'direccion': 'Avenida 10 Calle 5',
   'ciudad': 'Cartago',
   'telefono': '+506 3333-4444'},
  {'nombre': 'Carlos JimÃ©nez',
   'direccion': 'Calle Principal 12',
   'ciudad': 'Liberia',
   'telefono': '+506 6666-7777'},
  {'nombre': 'Diana Solano',
   'direccion': 'Barrio La UniÃ³n 78',
   'ciudad': 'Puntarenas',
   'telefono': '+506 9999-8888'}]}

##

## Extraer información usando regex:
### Utilice expresiones regulares para extraer la siguiente información de cada cliente:
- Nombre completo: Juan Pérez, María Gómez, Pedro Ramírez
- Dirección completa: Calle Mayor 123, Avenida Central 456, Barrio Escalante 789
- Ciudad: San José, Alajuela, Heredia
- Número de teléfono: +506 2222-3333, +506 8888-4444, +506 5555-6666

### Imprima la información extraída para cada cliente en un formato claro y organizado.


## Pistas:

- Utilice la librería re de Python para trabajar con expresiones regulares.
- Defina patrones de expresión regular específicos para cada tipo de información que desea extraer.
- Recorra el archivo JSON y aplique los patrones regex a cada cliente.
- Utilize métodos como findall() o search() para encontrar las coincidencias en el texto.

In [98]:
import json
import re

# Cargar el archivo JSON
try:
    with open("clientes.json", "r", encoding="utf-8") as archivo:
        clientes = json.load(archivo)
        cliente_nueva = json.dumps(clientes, ensure_ascii=False, indent=4)
except FileNotFoundError as e:
    print(f"Error: El archivo JSON 'clientes.json' no se encontró.")
except json.JSONDecodeError as e:
    print(f"Error al decodificar el archivo JSON: {e}")
except Exception as e:
    print(f"Error inesperado: {e}")

# Paso 3: Guardar la cadena JSON en un archivo de texto como código (cadena)
with open('archivo_clientes.txt', 'w', encoding='utf-8') as output_file:
    # Escribir la cadena JSON como texto de código en el archivo
    output_file.write(f'"{cliente_nueva}"')

with open('archivo_clientes.txt','r',encoding='utf-8') as archivo:
    archivo_clientes = archivo.read()

# La expresión busca "nombre", "direccion", "ciudad", y "telefono" seguidos de los valores que contienen.
patron = r'"nombre":\s*"([^"]+)"| "direccion":\s*"([^"]+)"| "ciudad":\s*"([^"]+)"| "telefono":\s*"([^"]+)"'

# Buscar todas las coincidencias con la expresión regular
coincidencias = re.findall(patron, archivo_clientes)

# Imprimir los resultados de las coincidencias
for i in range(0, len(coincidencias), 4):
    nombre = coincidencias[i][0]  # El nombre siempre estará en la primera captura
    direccion = coincidencias[i+1][1]  # Dirección en la segunda
    ciudad = coincidencias[i+2][2]  # Ciudad en la tercera
    telefono = coincidencias[i+3][3]  # Teléfono en la cuarta
    print(f"Nombre completo: {nombre}.")
    print(f"Dirección completa: {direccion}.")
    print(f"Ciudad: {ciudad}.")
    print(f"Número de teléfono: {telefono}.\n")

Nombre completo: Juan PÃ©rez.
Dirección completa: Calle Mayor 123.
Ciudad: San JosÃ©.
Número de teléfono: +506 2222-3333.

Nombre completo: MarÃ­a GÃ³mez.
Dirección completa: Avenida Central 456.
Ciudad: Alajuela.
Número de teléfono: +506 8888-4444.

Nombre completo: Pedro RamÃ­rez.
Dirección completa: Barrio Escalante 789.
Ciudad: Heredia.
Número de teléfono: +506 5555-6666.

Nombre completo: Ana Castro.
Dirección completa: Avenida 10 Calle 5.
Ciudad: Cartago.
Número de teléfono: +506 3333-4444.

Nombre completo: Carlos JimÃ©nez.
Dirección completa: Calle Principal 12.
Ciudad: Liberia.
Número de teléfono: +506 6666-7777.

Nombre completo: Diana Solano.
Dirección completa: Barrio La UniÃ³n 78.
Ciudad: Puntarenas.
Número de teléfono: +506 9999-8888.

